<html>
<title> Top book series</title>
<body bgcolor="aqua">
<h1 align="center">Top book series </h1>
<hr>
<hr>
<h2 align="center">NO.1 Percy Jackson series</h2>
<h3>The Percy Jackson series, it exibits gernres like action, comedy and hummor, mythology and emtional drama.<br>
The story begins when "The Minotaur(half human half bull)" kills Percy's mother and he and his friend Grover(a stray) escape to Camp Half blood.</br>
As you can see the story revoles around Greek mythology, it is not to miss series.</h3>
<hr>
<h2 align="center"> NO.2 Kane chronicles series</h2>
<h3>The Kane Chronicles series is based on Ancient Egyptian mythology and there are a lot of gods and backstories to keep track of.<br>
It follows siblings Carter and Sadie Kane as they reconnect after a significant tragedy kept them apart for so long.</br>
Despite their differences, they come together as the learn the truth about their family and the Kanes’ place in Egyptian history</h3>
<hr>
<h2 align="center">NO.3 The Heroes of Olympus</h2>
<h3>Camp half blood is astonised when a new demigod, Jason Grace arrives there.<br> 
They find out that he is a Roman demigod, while their hero Percy Jackson is missing and is in Jason's camp, Camp Jupiter.</br>
The two camps must put apart their diffrences and work together to defeat the all-mighty Gaia or better known as Mother Earth and her children the gaints </h3>
<hr>
<hr>
<h4 align="right">By Yodha Yarmaneni</h4>
</body>
</html>
